Zeitgeist.Appsco.Web/Controllers/LandingPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zeitgeist.Appsco.Web.App_Start;
using Zeitgeist.Appsco.Web.Models;

namespace Zeitgeist.Appsco.Web.Controllers
{
    public class LandingPageController : Controller
    {
        //
        // GET: /LandingPage/

        private readonly Manager manager = Manager.Instance;

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Save(LandingData id)
        {
            if (ModelState.IsValid)
            {
                if (manager.SaveClient(id))
                    return RedirectToAction("Message");

                return View("Index",id);
            }
            else
                return View("Index", id);
            
        }

        public ActionResult Message()
        {
            ViewBag.Message = "Se han Ingresado con exito tus Datos, te estaremos informando proximamente";
            return View();
        }

    }


}

Zeitgeist.Appsco.Web/Views/LandingPage/Index.cshtml
@model Zeitgeist.Appsco.Web.Models.LandingData
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Prodactive.co">
    <meta name="author" content="Zeitgeist.co">
    <meta name="google-site-verification" content="1T7VPOlWpbcwNErRLCKU2AQMRlEoLvIMom0qJMcjYOI" />
    <link rel="shortcut icon" href="assets/ico/favicon.png">

    <title> Prodactive </title>

    <!-- Bootstrap core CSS -->
    <link href="/Content/Landing/assets/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/Content/Landing/assets/css/main.css" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/Landing/assets/css/icomoon.css">
    <link href="~/Content/Landing/assets/css/animate-custom.css" rel="stylesheet">
    <link href="~/Content/Landing/css/LandingStyle.css" rel="stylesheet" />
    <link href="~/Content/Landing/css/hover.css" rel="stylesheet" />

    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>
    <script src="/Content/Landing/assets/js/jquery.min.js"></script>
    <script type="text/javascript" src="/Content/Landing/assets/js/modernizr.custom.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="assets/js/html5shiv.js"></script>
      <script src="assets/js/respond.min.js"></script>
    <![endif]-->
    
    <script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-53501429-1', 'auto');
    ga('send', 'pageview');

    </script>

</head>

<body data-spy="scroll" data-offset="0" data-target="#navbar-main">
    <div id="navbar-main">
        <!-- Fixed navbar -->
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container" style="top:5px;">
                <div style="text-align: center;">
                    <img src="~/Content/Landing/images/logo1.png" style="margin-top: 10px; max-width: 100%;" />
                </div>
            </div>
        </div>
    </div>
    <!-- ==== HEADERWRAP ==== -->
    <div id="headerwrap" id="home" name="home" style="position: relative; ">
        <!-- border-radius: 15px; -->
        <div class="col-lg-offset-7 col-lg-5  mod22" style="position: absolute; bottom: 40px; right: 10px; font-family:Impact;">
            <img src="~/Content/Landing/images/BumperG1.png" style="max-width: 100%;" />
            @*<h2>¡Activa tu Gente!</h2>
                <p>Mejoramos su salud empresarial invirtiendo en sus empleados.</p>*@
        </div>
    </div><!-- /headerwrap -->
    <!-- ==== GREYWRAP ==== -->
    <div id="greywrap">
        <div class="row">



            <div class="col-lg-4 callout">
                @*<span class="icon icon-stack"></span>*@
                <span class="icon buzz">
                    <img src="~/Content/Landing/images/Web%20Icon1.png" />
                </span>
                <h3>Plataforma Web</h3>
                <p>
                    Como empresa, publica y administra retos de actividad fisica, obten estadísticas e informes sobre el bienestar de tus empleados.
                </p>
            </div><!-- col-lg-4 -->




            <div class="col-lg-4 callout">
                @*<span class="icon icon-eye"></span>*@
                <span class="icon buzz">

                    <img src="~/Content/Landing/images/Web%20Icon2.png" />
                </span>
                <h3>Aplicación Movil</h3>
                <p>
                    Como empleado mide tu progreso y desempeño  en las actividades fisicas desde tu movil.
                    Participa en retos y recibe tips de interes.
                </p>
            </div><!-- col-lg-4 -->
            <div class="col-lg-4 callout">

                <span class="icon buzz">
                    <img src="~/Content/Landing/images/Web%20Icon3.png" />
                </span>

                <h3>Inscribete para dar el primer paso</h3>
                <a href="/Home/Index">
                    <button class="btn btn-default" type="submit">Inicia el reto.</button>
                </a>
                @{
    /*
     *  @using (Html.BeginForm("Save", "LandingPage", FormMethod.Post, new { role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    <div class="form-group">
                        <div class="input-group">

                            <div class="input-group-addon">
                                @@
                                @Html.TextBoxFor(model => model.Email, new { placeholder = "Email", @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Email)
                            </div>

                        </div>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-default" type="submit" value="Inscribete" />
                    </div>
                }
                     */
                }


            </div><!-- col-lg-4 -->
        </div><!-- row -->
    </div><!-- greywrap -->
    <div id="footerwrap" class="mod3">
        <div class="container" style="color:#FFFFFF;">
            <div class="social">
                Siguenos en <a href="https://www.facebook.com/prodactive.co" target="_blank"><img src="../../Content/Landing/images/Facebook_Icon.png" alt="" /></a>
                <a href="https://twitter.com/beprodactive" target="_blank"><img src="../../Content/Landing/images/Twitter_Icon.png" alt="" /></a>@*<a href="" target="_blank"><img src="../../Content/Landing/images/LinkedIn_Icon.png" alt="" /></a>*@
            </div>
            <h5 style="color:#FFFFFF;">Created by <a href="http://zeitgeist.com.co" style="color:#fafafa;font-weight:bold ">zeitgeist.com.co</a> - Copyright 2014</h5>
        </div>
    </div>

    <!-- Bootstrap core JavaScript
        ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->


    <script type="text/javascript" src="assets/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="assets/js/retina.js"></script>
    <script type="text/javascript" src="assets/js/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="assets/js/smoothscroll.js"></script>
    <script type="text/javascript" src="assets/js/jquery-func.js"></script>
</body>

</html>

Zeitgeist.Appsco.Web/Views/LandingPage/Message.cshtml
@{
    ViewBag.Title = "Message";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}
@model Zeitgeist.Appsco.Web.Models.LandingData
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="SHIELD - Free Bootstrap 3 Theme">
    <meta name="author" content="Carlos Alvarez - Alvarez.is - blacktie.co">
    <link rel="shortcut icon" href="assets/ico/favicon.png">

    <title> Landing pag</title>

    <!-- Bootstrap core CSS -->
    <link href="/Content/Landing/assets/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/Content/Landing/assets/css/main.css" rel="stylesheet">
    <link rel="stylesheet" href="/Content/Landing/assets/css/icomoon.css">
    <link href="/Content/Landing/assets/css/animate-custom.css" rel="stylesheet">
    <link href="~/Content/Landing/css/LandingStyle.css" rel="stylesheet" />
    <link href="~/Content/Landing/css/hover.css" rel="stylesheet" />

    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>
    <script src="/Content/Landing/assets/js/jquery.min.js"></script>
    <script type="text/javascript" src="/Content/Landing/assets/js/modernizr.custom.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="assets/js/html5shiv.js"></script>
      <script src="assets/js/respond.min.js"></script>
    <![endif]-->
</head>

<body data-spy="scroll" data-offset="0" data-target="#navbar-main">


    <div id="navbar-main">
        <!-- Fixed navbar -->
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div style="text-align: center;"><img src="~/Content/Landing/images/logo.png" style="width:40%;height: 40%" /></div>
            </div>
        </div>
    </div>
    <!-- ==== HEADERWRAP ==== -->
    <div id="headerwrap" id="home" name="home" style="position: relative; ">
        <div class="row" style="height:700px">
            <div  >
                                @*<p>
        class=" container col-lg-offset-4 col-lg-4" style="width:500px; height:100px;top:220px;
                 ¡prepárate, pronto te informaremos!
                </p>*@
                <img src="../../Content/Landing/images/Mensaje_teinf.png" style="width:100%;margin-top:250px;" alt="" />
            </div>
        </div>

    </div><!-- /headerwrap -->
    <!-- ==== GREYWRAP ==== -->
    <div id="greywrap">
        <div class="row">
            
        </div>
    </div><!-- greywrap -->
    <div id="footerwrap" class="mod3">
        <div class="container">
            <h5>Created by <a href="http://zeitgeist.com.co" style="color:#FFFFFF;font-weight:bold ">zeitgeist.com.co</a> - Copyright 2014</h5>
        </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->


    <script type="text/javascript" src="assets/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="assets/js/retina.js"></script>
    <script type="text/javascript" src="assets/js/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="assets/js/smoothscroll.js"></script>
    <script type="text/javascript" src="assets/js/jquery-func.js"></script>
</body>
</html>